apiVersion: v1
kind: Pod
metadata:
  name: tailscale-subnet-router
spec:
  serviceAccountName: tailscale
  containers:
  - name: tailscale
    imagePullPolicy: Always
    image: ghcr.io/tailscale/tailscale:latest
    env:
    # Store the state in a k8s secret
    - name: TS_KUBE_SECRET
      value: tailscale-state
    - name: TS_USERSPACE
      value: "true"
    - name: TS_AUTH_KEY
      valueFrom:
        secretKeyRef:
          name: tailscale-auth
          key: TS_AUTH_KEY
          optional: true
    - name: TS_ROUTES
      value: 192.168.0.0/23
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
