---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    {{- include "app.labels" . | indent 4 }}
  annotations:
    {{- include "app.annotations" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | indent 6 }}
  serviceName: {{ include "app.name" . }}
  template:
    metadata:
      labels:
        {{- include "app.labels" . | indent 8 }}
{{ with .Values.podLabels }}{{ toYaml . | indent 8 }}{{ end }}
      annotations:
        checksum/configMap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- include "app.annotations" . | indent 8 }}
{{ with .Values.podAnnotations }}{{ toYaml . | indent 8 }}{{ end }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      serviceAccountName: {{ template "app.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.command }}
          command: {{ toYaml . | nindent 16 }}
          {{- end }}
          {{- with .Values.args }}
          args: {{ toYaml . | nindent 16 }}
          {{- end }}
          env:
            - name: TAILSCALED_STATE
              value: kube:{{ .Values.rbac.stateSecretName }}
          envFrom:
            - configMapRef:
                name: {{ template "app.fullname" . }}-config
            - secretRef:
                name: {{ template "app.fullname" . }}-config
          ports:
            - name: exporter
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: lib-modules
              mountPath: /lib/modules
          {{- with .Values.livenessProbe }}
          livenessProbe: {{ toYaml . | nindent 16 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe: {{ toYaml . | nindent 16 }}
          {{- end }}
          {{- with .Values.resources }}
          resources: {{ toYaml . | nindent 16 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext: {{ toYaml . | nindent 16 }}
          {{- end }}
      volumes:
        - name: lib-modules
          hostPath:
            path: /lib/modules
      {{- with .Values.hostAliases }}
      hostAliases: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
